### ISSUE TITLE
Fix flaky PostsController joined_at test

### ISSUE THREAD

**Issue by Throne3d** [glowfic-constellation/glowfic#1817]
```
Failures:

  1) PostsController PUT update make changes with author changes correctly updates when adding new authors
     Failure/Error: expect(main_author.joined_at).to be_the_same_time_as(post.created_at)

       expected 2023-10-13 18:43:16 -0400 to be the same time as 2023-10-13 18:43:17 -0400
       compared: 2023-10-13T18:43:16-04:00
           with: 2023-10-13T18:43:17-04:00
     # ./spec/controllers/posts/update_spec.rb:665:in `block (4 levels) in <top (required)>'
```

e.g. https://github.com/glowfic-constellation/glowfic/actions/runs/6513733312/job/17693836167, disappears on retry
