### ISSUE TITLE
Present character nicknames as tags rather than comma-separated list

### ISSUE THREAD

**Issue by Throne3d** [glowfic-constellation/glowfic#1830]
https://discord.com/channels/521407923629457428/608751226364100619/1165222823250362378

![image](https://github.com/glowfic-constellation/glowfic/assets/577128/3e093d5f-b81a-4a70-b1e5-33b3700b3981)

By switching to `ul`/`li` and using:

```css
.character-template-nickname ul {
    list-style: inside none none;
    padding: 0;
    margin: 0;
}
.character-template-nickname li {
    display: inline-block;
    background: #25262E;
    margin: .2em;
    padding: .1em .5em;
    border-radius: .5em;
}
```

Could also apply to e.g. settings on this page?
